### ISSUE TITLE
Shouldn't this be less than instead of less than or equal

### ISSUE THREAD

**Issue by johnyoonh** [bnlucas/python-basehash#5]
https://github.com/bnlucas/python-basehash/blob/a79581fda56895e65bdada92d90e70ca45f00c06/basehash/__init__.py#L36

**Comment by johnyoonh** [comment]
BASE_CHARACTER_SET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz-_'
base64u = basehash.base(django_settings.BASE_CHARACTER_SET)
base64u.encode(0)
This causes error

base64u.encode(1) returns 'B'

Simply moving the equal sign doesn't fix the problem as 0 will cause the loop to never exit

**Comment by bnlucas** [comment]
This has been updated with https://github.com/bnlucas/python-basehash/pull/9#merged-event
